application:
  version: 1.0.0
  title: spring boot batch

logging:
  file:
    path: logs   
    max-size: 10MB
    max-history: 10
  level:
    root: warn
    com.autumnia.batch: debug
    
spring:
   main:
      banner-mode: "off"
   profiles:
      active: dev   
   output:
      ansi:
         enabled: detect
   datasource:
      plaform: mysql
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring
      username: root
      password: root
      initialization-mode: never
      


   