server:
   port: 8080
   servlet:
      encoding:
         charset: UTF-8
         force: true         
   tomcat:
      uri-encoding: UTF-8         
         
logging:
   level:
      com.autumnia.jwtservice: DEBUG   

spring:
   main:
      banner-mode: off

   application: 
      name: jwt-service

   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
         
   h2:
      console:
         enabled: true
#         path: /h2-console
#         settings:
#            web-allow-others: true

   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:          

   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
#           del-auto: update
         ddl-auto: create-drop   # drop -> create -> alter  -> drop(종료)
      properties:
         hibernate:
            format_sql: true
            show_sql: true                   
      defer-datasource-initialization: true     
   
jwt:
   header: Authorization
   #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
   #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
   secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
   token-validity-in-seconds: 43200 # 86400