server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

# ERROR WARN INFO DEBUG ERROR TRACE
logging:
  level:
    "[org.springframework.boot.web]": INFO
    "[com.autumnia.junitprj]": DEBUG
    "[org.hibernate]": INFO
